import org.graalvm.nativeimage.c.CContext;
import org.graalvm.nativeimage.c.constant.CEnum;
import org.graalvm.nativeimage.c.constant.CEnumLookup;
import org.graalvm.nativeimage.c.constant.CEnumValue;

@CContext(HashLink.HL.class)
public class COpcode {
    @CEnum
    public enum hl_op {

        OMov,
        OInt,
        OFloat,
        OBool,
        OBytes,
        OString,
        ONull,
        OAdd,
        OSub,
        OMul,
        OSDiv,
        OUDiv,
        OSMod,
        OUMod,
        OShl,
        OSShr,
        OUShr,
        OAnd,
        OOr,
        OXor,
        ONeg,
        ONot,
        OIncr,
        ODecr,
        OCall0,
        OCall1,
        OCall2,
        OCall3,
        OCall4,
        OCallN,
        OCallMethod,
        OCallThis,
        OCallClosure,
        OStaticClosure,
        OInstanceClosure,
        OVirtualClosure,
        OGetGlobal,
        OSetGlobal,
        OField,
        OSetField,
        OGetThis,
        OSetThis,
        ODynGet,
        ODynSet,
        OJTrue,
        OJFalse,
        OJNull,
        OJNotNull,
        OJSLt,
        OJSGte,
        OJSGt,
        OJSLte,
        OJULt,
        OJUGte,
        OJNotLt,
        OJNotGte,
        OJEq,
        OJNotEq,
        OJAlways,
        OToDyn,
        OToSFloat,
        OToUFloat,
        OToInt,
        OSafeCast,
        OUnsafeCast,
        OToVirtual,
        OLabel,
        ORet,
        OThrow,
        ORethrow,
        OSwitch,
        ONullCheck,
        OTrap,
        OEndTrap,
        OGetI8,
        OGetI16,
        OGetMem,
        OGetArray,
        OSetI8,
        OSetI16,
        OSetMem,
        OSetArray,
        ONew,
        OArraySize,
        OType,
        OGetType,
        OGetTID,
        ORef,
        OUnref,
        OSetref,
        OMakeEnum,
        OEnumAlloc,
        OEnumIndex,
        OEnumField,
        OSetEnumField,
        OAssert,
        ORefData,
        ORefOffset,
        ONop,
        OLast;

        @CEnumValue
        public native int getCValue();

        @CEnumLookup
        public static native hl_op fromCValue(int var1);
    }

}
